/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 19 10:37:00 GMT 2019
 */

package jbhembise.testauto.example6;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import java.util.List;
import jbhembise.testauto.example6.Media;
import jbhembise.testauto.example6.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class User_ESTest extends User_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      User user0 = new User("", (String) null);
      String string0 = user0.getLastName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      User user0 = new User("~%vC!Jibj{L9;A5e", "~%vC!Jibj{L9;A5e");
      String string0 = user0.getLastName();
      assertEquals("~%vC!Jibj{L9;A5e", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      User user0 = new User("6CuFnKKr}m_P@LAG*", (String) null);
      String string0 = user0.getFirstName();
      assertEquals("6CuFnKKr}m_P@LAG*", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      User user0 = new User("", "");
      String string0 = user0.getFirstName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      User user0 = new User("6CuFnKKr}m_P@LAG*", (String) null);
      Media media0 = mock(Media.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(media0).toString();
      user0.borrow(media0);
      List<Media> list0 = user0.getBorrowedMedias();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      User user0 = new User("", "");
      String string0 = user0.getLastName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      User user0 = new User("6CuFnKKr}m_P@LAG*", (String) null);
      List<Media> list0 = user0.getBorrowedMedias();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      User user0 = new User((String) null, (String) null);
      String string0 = user0.getFirstName();
      assertNull(string0);
  }
}
