/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 19 10:23:46 GMT 2019
 */

package jbhembise.testauto.example5;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import jbhembise.testauto.example5.DVD;
import jbhembise.testauto.example5.Media;
import jbhembise.testauto.example5.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class User_ESTest extends User_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      User user0 = new User("jbhembise.testauto.example5.DVD", "jbhembise.testauto.example5.DVD");
      String string0 = user0.getLastName();
      assertEquals("jbhembise.testauto.example5.DVD", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      User user0 = new User("", "");
      String string0 = user0.getLastName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      User user0 = new User((String) null, (String) null);
      String string0 = user0.getFirstName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      User user0 = new User("d8\"\"G", "");
      String string0 = user0.getFirstName();
      assertEquals("", user0.getLastName());
      assertEquals("d8\"\"G", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      User user0 = new User("", "");
      DVD dVD0 = new DVD("u8 |i", (-4037));
      user0.borrow(dVD0);
      List<Media> list0 = user0.getBorrowedMedias();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      User user0 = new User((String) null, (String) null);
      String string0 = user0.getLastName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      User user0 = new User("", "");
      List<Media> list0 = user0.getBorrowedMedias();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      User user0 = new User("", "2T1-");
      String string0 = user0.getFirstName();
      assertEquals("2T1-", user0.getLastName());
      assertEquals("", string0);
  }
}
