/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 20 07:58:50 GMT 2019
 */

package jbhembise.testauto.example1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import jbhembise.testauto.example1.Calculator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Calculator_ESTest extends Calculator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      calculator0.add((-330));
      assertEquals((-330), calculator0.getResult());
      
      calculator0.divide((-1736));
      assertEquals(0, calculator0.getResult());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      calculator0.multiply(2541);
      assertEquals(0, calculator0.getResult());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      calculator0.add(234);
      int int0 = calculator0.getResult();
      assertEquals(234, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      calculator0.add((-330));
      int int0 = calculator0.getResult();
      assertEquals((-330), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      calculator0.substract(1);
      assertEquals((-1), calculator0.getResult());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      calculator0.multiply(0);
      assertEquals(0, calculator0.getResult());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      calculator0.clear();
      assertEquals(0, calculator0.getResult());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.getResult();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      // Undeclared exception!
      try { 
        calculator0.divide(0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("jbhembise.testauto.example1.Calculator", e);
      }
  }
}
