/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 20 08:28:41 GMT 2019
 */

package jbhembise.testauto.example7;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import jbhembise.testauto.example7.Email;
import jbhembise.testauto.example7.EmailDto;
import jbhembise.testauto.example7.EmailMapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmailMapper_ESTest extends EmailMapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[1];
      Email email0 = new Email("apzH)v7]CSCU5u06D", "apzH)v7]CSCU5u06D", "/.wHjv/2", stringArray0);
      assertEquals("/.wHjv/2", email0.getFrom());
      assertEquals("apzH)v7]CSCU5u06D", email0.getContent());
      assertEquals("apzH)v7]CSCU5u06D", email0.getSubject());
      assertNotNull(email0);
      assertEquals(1, stringArray0.length);
      
      EmailDto emailDto0 = EmailMapper.toDto(email0);
      assertEquals("/.wHjv/2", email0.getFrom());
      assertEquals("apzH)v7]CSCU5u06D", email0.getContent());
      assertEquals("apzH)v7]CSCU5u06D", email0.getSubject());
      assertEquals("apzH)v7]CSCU5u06D", emailDto0.getSubject());
      assertEquals("/.wHjv/2", emailDto0.getFrom());
      assertEquals("apzH)v7]CSCU5u06D", emailDto0.getContent());
      assertNotNull(emailDto0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EmailMapper emailMapper0 = new EmailMapper();
      assertNotNull(emailMapper0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        EmailMapper.toDto((Email) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("jbhembise.testauto.example7.EmailMapper", e);
      }
  }
}
