/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 18 13:49:33 GMT 2019
 */

package jbhembise.testauto.example4;

import org.junit.Test;
import static org.junit.Assert.*;
import jbhembise.testauto.example4.FizzBuzz;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FizzBuzz_ESTest extends FizzBuzz_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = FizzBuzz.fizzbuzz(0);
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = FizzBuzz.fizzbuzz(1600);
      assertEquals("Buzz", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = FizzBuzz.fizzbuzz(3975);
      assertEquals("FizzBuzz", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = FizzBuzz.fizzbuzz(494);
      assertEquals("494", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = FizzBuzz.fizzbuzz(12);
      assertEquals("Fizz", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = FizzBuzz.fizzbuzz((-501));
      assertEquals("-501", string0);
  }
}
